require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'FirstTSApp2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'FirstTSApp2Tests' do
    inherit! :complete
    # Pods for testing
  end


end

target 'FirstTSApp2-tvOS' do
  # Pods for FirstTSApp2-tvOS

  target 'FirstTSApp2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
